sil-student-projects/2018-android

README.md

- Yes, all I did was add the Contributors section.

Fixed #1 Added myself and Contributors to README

---

README.md

Add a new bullet point to the README with my name

README: Add myself as a contributor

---

README.md

Added an additional contributor to the README.MD file for the Android App Development Project (2018).

Changes to README.MD - Contributors Added - Joseph Jinn.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/res/layout/activity_entry.xml
app/src/main/res/layout/activity_session.xml
app/src/main/res/values/strings.xml

Generate blank activities for each screen

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/MainActivity.java
app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/res/drawable/ic_add_white_24dp.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/session_list_item.xml
app/src/main/res/values/styles.xml

Draft session list screen layout

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/res/layout/activity_entry.xml
app/src/main/res/layout/entry_field_item.xml
app/src/main/res/layout/fragment_entry.xml
app/src/main/res/values/strings.xml

Draft lexical entry page

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/res/layout/activity_session.xml

Apologies on the branch name, I wasn't sure what I was going to be working on when I created it and then I forgot to rebranch.

Further features on the session create page, specifically around time collection

---

app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/java/org/sil/gatherwords/room/AppDatabase.java

Switch db usage to singleton

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/java/org/sil/gatherwords/room/WordDao.java

TODO: This does not yet populate individual fields.
See #76

Lexical entry: Read word data from the db

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java

Fields at the top, followed by methods (trying to keep dependant methods together), then other classes

Rearrange code

---

app/src/androidTest/java/org/sil/gatherwords/room/AppDatabaseTest.java
app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/java/org/sil/gatherwords/room/AppDatabase.java
app/src/main/java/org/sil/gatherwords/room/Meaning.java
app/src/main/java/org/sil/gatherwords/room/MeaningDao.java
app/src/main/java/org/sil/gatherwords/room/WordDao.java

Split word.meanings into separate table

---

app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/java/org/sil/gatherwords/room/FilledWord.java
app/src/main/java/org/sil/gatherwords/room/WordDao.java

Lexical entry: Populate fields with data from db

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/room/AppDatabase.java
app/src/main/java/org/sil/gatherwords/room/Word.java
app/src/main/java/org/sil/gatherwords/room/WordDao.java
app/src/main/res/drawable/ic_delete_red_24dp.xml
app/src/main/res/menu/entry_menu.xml
app/src/main/res/values/strings.xml

Lexical Entry: Implement delete

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/java/org/sil/gatherwords/room/FilledWord.java
app/src/main/res/layout/fragment_entry.xml

Entry: Move image into ListView

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/room/AppDatabase.java
app/src/main/java/org/sil/gatherwords/room/Word.java
app/src/main/res/values/strings.xml

Audio: Save to separate files

---

app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/res/layout/activity_entry.xml
app/src/main/res/layout/fragment_entry.xml
app/src/main/res/values/array.xml

-Many thanks to Andrew Thomas for his help. =D
FIXES #106

Bug fixed - ScrollView does not extend below footer.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/124)

Readme: Fix setup instructions

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/MainActivity.java
app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/java/org/sil/gatherwords/UploadService.java
app/src/main/java/org/sil/gatherwords/room/AppDatabase.java
app/src/main/java/org/sil/gatherwords/room/Converters.java
app/src/main/java/org/sil/gatherwords/room/Session.java
app/src/main/java/org/sil/gatherwords/room/SessionDao.java
app/src/main/java/org/sil/gatherwords/room/Word.java
app/src/main/java/org/sil/gatherwords/room/WordDao.java
app/src/main/res/values/strings.xml

No network access implemented.  Icon does not appear to load correctly.
Test usage with:
```java
Intent uploadIntent = new Intent(getApplicationContext(), UploadService.class);
uploadIntent.putExtra(SessionActivity.ARG_SESSION_ID, session.id);
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
startForegroundService(uploadIntent);
}
else {
startService(uploadIntent);
}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/125)

Create framework service to manage background uploads

---

app/src/androidTest/java/org/sil/gatherwords/room/AppDatabaseTest.java
app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/java/org/sil/gatherwords/MainActivity.java
app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/java/org/sil/gatherwords/UploadService.java
app/src/main/java/org/sil/gatherwords/room/AppDatabase.java
app/src/main/java/org/sil/gatherwords/room/MeaningDAO.java
app/src/main/java/org/sil/gatherwords/room/SessionDAO.java
app/src/main/java/org/sil/gatherwords/room/WordDAO.java

DAO is an acronym, and so should be all caps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/126)

Naming: Make capitalization consistent (no functional change)

---

app/src/main/java/org/sil/gatherwords/MainActivity.java
app/src/main/java/org/sil/gatherwords/room/Progress.java
app/src/main/java/org/sil/gatherwords/room/SessionDAO.java
app/src/main/java/org/sil/gatherwords/room/SessionMeta.java
app/src/main/res/layout/session_list_item.xml

Fixes #123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/128)

Session List: Display progress of audio collection

---

app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/java/org/sil/gatherwords/room/FilledWord.java
app/src/main/java/org/sil/gatherwords/room/WordDAO.java
app/src/main/res/layout/entry_audio_status.xml
app/src/main/res/values/strings.xml

Fixes #122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/129)

Entry: Display if item has recorded audio

---

app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/java/org/sil/gatherwords/room/AppDatabase.java
app/src/main/java/org/sil/gatherwords/room/DatabaseSeeder.java
app/src/main/java/org/sil/gatherwords/room/FilledWord.java
app/src/main/java/org/sil/gatherwords/room/SemanticDomain.java
app/src/main/java/org/sil/gatherwords/room/SemanticDomainDAO.java
app/src/main/java/org/sil/gatherwords/room/Word.java
app/src/main/java/org/sil/gatherwords/room/WordDAO.java

Fixes #120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/130)

Semantic Domain: Parse/load autocomplete list asynchronously

---

app/src/main/java/org/sil/gatherwords/EntryFragment.java

Fixes #115
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/132)

Lexical Entry: Fix save fails when there are too many meanings

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/ImageCapture.java
app/src/main/res/layout/activity_entry.xml

Aids readability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/134)

Image Capture: Extract to separate class (no functional change)

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java
app/src/main/java/org/sil/gatherwords/EntryFragment.java
app/src/main/java/org/sil/gatherwords/ImageCapture.java
app/src/main/java/org/sil/gatherwords/MainActivity.java
app/src/main/java/org/sil/gatherwords/SessionActivity.java
app/src/main/java/org/sil/gatherwords/UploadService.java
app/src/main/java/org/sil/gatherwords/Util.java
app/src/main/java/org/sil/gatherwords/room/DatabaseSeeder.java
app/src/main/java/org/sil/gatherwords/room/FilledWord.java
app/src/main/java/org/sil/gatherwords/room/Meaning.java
app/src/main/java/org/sil/gatherwords/room/MeaningDAO.java
app/src/main/java/org/sil/gatherwords/room/SemanticDomain.java
app/src/main/java/org/sil/gatherwords/room/Session.java
app/src/main/java/org/sil/gatherwords/room/SessionDAO.java
app/src/main/java/org/sil/gatherwords/room/SessionMeta.java
app/src/main/java/org/sil/gatherwords/room/Word.java
app/src/main/java/org/sil/gatherwords/room/WordDAO.java
app/src/main/res/values/strings.xml

Fixes #51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/140)

DB: Purify api

---

app/src/main/java/org/sil/gatherwords/EntryActivity.java

Fixes #127
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/135)

Audio Recorder: Change source for better volume

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/sil/gatherwords/MainActivity.java
app/src/main/java/org/sil/gatherwords/Uploader.java
app/src/main/res/layout/session_list_item.xml

Requires registering the app [sha1](https://stackoverflow.com/a/34223470/923712) in your [console](https://stackoverflow.com/a/41012703).
Fixes #36
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/144)

Upload: Get oauth2 token from Google

---

app/src/main/java/org/sil/gatherwords/Uploader.java
app/src/main/java/org/sil/gatherwords/Util.java
app/src/main/java/org/sil/gatherwords/XForgeAPI.java
app/src/main/res/values/strings.xml

Untested due to missing upstream implementation.
See #139
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sil-student-projects/2018-android/145)

Upload: Draft login procedure
